# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf

module CustomType
    class Prefecture
      List = ["Sapporo",
        "Aomori",
        "Morioka",
        "Sendai",
        "Akita",
        "Yamagata",
        "Fukushima",
        "Mito",
        "Utsunomiya",
        "Maebashi",
        "Saitama",
        "Chiba",
        "Shinjuku",
        "Yokohama",
        "Niigata",
        "Toyama",
        "Kanazawa",
        "Fukui",
        "Kofu",
        "Nagano",
        "Gifu",
        "Shizuoka",
        "Nagoya",
        "Tsu",
        "Otsu",
        "Kyouto",
        "Osaka",
        "Koube",
        "Nara",
        "Wakayama",
        "Tottori",
        "Matsue",
        "Okayama",
        "Hiroshima",
        "Yamaguchi",
        "Tokushima",
        "Takamatsu",
        "Matsuyama",
        "Kochi",
        "Fukuoka",
        "Saga",
        "Nagasaki",
        "Kumamoto",
        "Oita",
        "Miyazaki",
        "Kagoshima",
        "Naha"]
    end
  end
